name: Setup latest .NET SDKs
author: Els_kom
description: Github Action to install the daily builds of the .NET SDK.

inputs:
    VERSION_MAJOR:
        description: Major version of the .NET SDK to install.
        required: false
        default: '6'
    VERSION_MINOR:
        description: Minor version of the .NET SDK to install.
        required: false
        default: '0'

runs:
    using: node12
    main: index.js

branding:
    icon: download-cloud
    color: blue
